#!/usr/bin/env bash
# Fetch secrets from GCP Secret Manager and write to .env
# Usage: ./system/fetch_secrets.sh [PROJECT_ID]

set -euo pipefail

PROJECT_ID="${1:-osteotwin}"
ENV_FILE="$(dirname "$0")/../.env"

echo "Fetching secrets from GCP project: ${PROJECT_ID}"

fetch_secret() {
  local secret_id="$1"
  gcloud secrets versions access latest \
    --secret="$secret_id" \
    --project="$PROJECT_ID" \
    2>/dev/null || echo ""
}

ANTHROPIC_KEY=$(fetch_secret "anthropic-api-key")
GEMINI_KEY=$(fetch_secret "gemini-api-key")
JWT_SECRET=$(fetch_secret "jwt-secret-key")
SIM_KEY=$(fetch_secret "sim-api-key")
NEO4J_PASS=$(fetch_secret "neo4j-password")
ADMIN_PASS=$(fetch_secret "admin-password")

cat > "$ENV_FILE" <<EOF
# Auto-generated by fetch_secrets.sh — do not commit
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}
GEMINI_API_KEY=${GEMINI_KEY}
JWT_SECRET_KEY=${JWT_SECRET}
SIM_API_KEY=${SIM_KEY}
NEO4J_PASSWORD=${NEO4J_PASS}
ADMIN_USERNAME=admin
ADMIN_PASSWORD=${ADMIN_PASS}

# Server binding
PLAN_HOST=0.0.0.0
PLAN_PORT=8200
SIM_HOST=0.0.0.0
SIM_PORT=8300
SIMULATION_SERVER_URL=http://localhost:8300

# Neo4j
NEO4J_URI=bolt://localhost:7687
NEO4J_USER=neo4j

# Models
CLAUDE_MODEL_FAST=claude-sonnet-4-20250514
CLAUDE_MODEL_SMART=claude-sonnet-4-20250514
GEMINI_MODEL=gemini-2.5-flash

# GCP
GCP_PROJECT_ID=${PROJECT_ID}
EOF

echo "Secrets written to ${ENV_FILE}"
