#!/usr/bin/env bash
# One-time GCP project setup for OsteoTwin
# Prerequisites: gcloud CLI authenticated, terraform installed
#
# This script:
#   1. Creates the GCP project via Terraform
#   2. Copies API keys from the existing ROBOT4KID project
#   3. Generates new secrets (JWT, SIM_API_KEY) for OsteoTwin
#   4. Stores everything in GCP Secret Manager
#   5. Writes local .env file
#
# Usage: bash system/setup_gcp.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TERRAFORM_DIR="$PROJECT_ROOT/infra/terraform"
ROBOT4KID_PROJECT="nl2bot-f7e604"

echo "=== OsteoTwin GCP Setup ==="

# Step 1: Ensure gcloud auth
echo "[1/5] Checking gcloud authentication..."
if ! gcloud auth list --filter="status:ACTIVE" --format="value(account)" 2>/dev/null | head -1 | grep -q "@"; then
  echo "  Not authenticated. Running 'gcloud auth login'..."
  gcloud auth login
  gcloud auth application-default login
fi

# Step 2: Terraform init & apply
echo "[2/5] Creating GCP project via Terraform..."
cd "$TERRAFORM_DIR"
terraform init
terraform apply -auto-approve
OSTEOTWIN_PROJECT=$(terraform output -raw project_id)
echo "  Created project: $OSTEOTWIN_PROJECT"

# Step 3: Copy API keys from ROBOT4KID
echo "[3/5] Copying API keys from ROBOT4KID project..."
ANTHROPIC_KEY=$(gcloud secrets versions access latest --secret="anthropic-api-key" --project="$ROBOT4KID_PROJECT")
GEMINI_KEY=$(gcloud secrets versions access latest --secret="gemini-api-key" --project="$ROBOT4KID_PROJECT")

# Step 4: Generate new secrets for OsteoTwin
echo "[4/5] Generating new secrets..."
JWT_SECRET=$(openssl rand -hex 32)
SIM_API_KEY=$(openssl rand -hex 24)
NEO4J_PASS=$(openssl rand -hex 16)

# Store in GCP Secret Manager
store_secret() {
  local id="$1" val="$2"
  echo -n "$val" | gcloud secrets versions add "$id" --data-file=- --project="$OSTEOTWIN_PROJECT" 2>/dev/null || \
  echo -n "$val" | gcloud secrets versions add "$id" --data-file=- --project="$OSTEOTWIN_PROJECT"
}

store_secret "anthropic-api-key" "$ANTHROPIC_KEY"
store_secret "gemini-api-key" "$GEMINI_KEY"
store_secret "jwt-secret-key" "$JWT_SECRET"
store_secret "sim-api-key" "$SIM_API_KEY"
store_secret "neo4j-password" "$NEO4J_PASS"

# Step 5: Write local .env
echo "[5/5] Writing .env file..."
cat > "$PROJECT_ROOT/.env" <<EOF
# OsteoTwin — auto-generated by setup_gcp.sh
# GCP Project: $OSTEOTWIN_PROJECT
ANTHROPIC_API_KEY=$ANTHROPIC_KEY
GEMINI_API_KEY=$GEMINI_KEY
JWT_SECRET_KEY=$JWT_SECRET
SIM_API_KEY=$SIM_API_KEY
NEO4J_PASSWORD=$NEO4J_PASS

PLAN_HOST=0.0.0.0
PLAN_PORT=8200
SIM_HOST=0.0.0.0
SIM_PORT=8300
SIMULATION_SERVER_URL=http://localhost:8300

NEO4J_URI=bolt://localhost:7687
NEO4J_USER=neo4j

CLAUDE_MODEL_FAST=claude-sonnet-4-20250514
CLAUDE_MODEL_SMART=claude-sonnet-4-20250514
GEMINI_MODEL=gemini-2.5-flash

GCP_PROJECT_ID=$OSTEOTWIN_PROJECT
EOF

echo ""
echo "=== Setup complete ==="
echo "  GCP Project: $OSTEOTWIN_PROJECT"
echo "  .env written to: $PROJECT_ROOT/.env"
echo ""
echo "Next steps:"
echo "  1. cd $PROJECT_ROOT"
echo "  2. python -m venv .venv && source .venv/Scripts/activate"
echo "  3. pip install -r planning_server/requirements.txt"
echo "  4. pip install -r simulation_server/requirements.txt"
echo "  5. cd dashboard && npm install && cd .."
echo "  6. powershell -File system/services.ps1 install  # (as Admin)"
echo "  7. powershell -File system/services.ps1 start"
echo "  8. cd dashboard && npm run dev  # React dashboard on :5173"
